import type { Metadata } from "next";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    projects,
}: Readonly<{
    children: React.ReactNode;
    projects: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                {children}
                <div>{projects}</div>
            </body>
        </html>
    );
}
